version: 2

project_name: repo-manager

builds:
  - id: repo
    main: ./cmd/repo
    binary: repo
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

release:
  name_template: 'v{{.Version}}'

changelog:
  sort: asc